[project]
name = "simcore-sdk"
version = "1.3.1"
description = "Simcore SDK for interacting with osparc"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "simcore-common-library",
  "simcore-models-library",
  "simcore-settings-library",
  "simcore-service-library",
  "simcore-postgres-database",
  "aiocache",
  "aiofiles",
  "aiohttp>=3.7.4,!=3.11.13",
  "httpx>=0.23.0,!=0.28.0",
  "packaging",
  "pint",
  "pydantic[email]>=2.10.0,<2.12.0",
  "sqlalchemy[asyncio]>=1.3.3,<2.0",
  "tenacity",
  "tqdm",
]

[project.optional-dependencies]
test = [
  "aioboto3==15.1.0",
  "aiobotocore==2.24.0",
  "aiofiles==24.1.0",
  "aiohappyeyeballs==2.6.1",
  "aiohttp==3.12.15",
  "aioitertools==0.12.0",
  "aioresponses==0.7.8",
  "aiosignal==1.4.0",
  "alembic==1.16.5",
  "annotated-types==0.7.0",
  "antlr4-python3-runtime==4.13.2",
  "attrs==25.3.0",
  "aws-sam-translator==1.100.0",
  "aws-xray-sdk==2.14.0",
  "blinker==1.9.0",
  "boto3==1.39.11",
  "botocore-stubs==1.40.33",
  "botocore==1.39.11",
  "certifi==2025.8.3",
  "cffi==2.0.0",
  "cfn-lint==1.40.0",
  "charset-normalizer==3.4.3",
  "click==8.3.0",
  "coverage==7.10.7",
  "cryptography==46.0.2",
  "docker==7.1.0",
  "execnet==2.1.1",
  "faker==37.8.0",
  "flaky==3.8.1",
  "flask-cors==6.0.1",
  "flask==3.1.2",
  "frozenlist==1.7.0",
  "graphql-core==3.2.6",
  "greenlet==3.2.4",
  "icdiff==2.0.7",
  "idna==3.10",
  "iniconfig==2.1.0",
  "itsdangerous==2.2.0",
  "jinja2==3.1.6",
  "jmespath==1.0.1",
  "joserfc==1.3.4",
  "jsonpatch==1.33",
  "jsonpath-ng==1.7.0",
  "jsonpointer==3.0.0",
  "jsonschema-path==0.3.4",
  "jsonschema-specifications==2025.9.1",
  "jsonschema==4.25.1",
  "lazy-object-proxy==1.12.0",
  "mako==1.3.10",
  "markupsafe==3.0.3",
  "moto==5.1.13",
  "mpmath==1.3.0",
  "multidict==6.6.4",
  "mypy-extensions==1.1.0",
  "mypy==1.18.2",
  "networkx==3.5",
  "openapi-schema-validator==0.6.3",
  "openapi-spec-validator==0.7.2",
  "packaging==25.0",
  "pathable==0.4.4",
  "pathspec==0.12.1",
  "pluggy==1.6.0",
  "ply==3.11",
  "pprintpp==0.4.0",
  "propcache==0.3.2",
  "py-partiql-parser==0.6.1",
  "pycparser==2.23",
  "pydantic-core==2.33.2",
  "pydantic==2.11.9",
  "pygments==2.19.2",
  "pyparsing==3.2.5",
  "pytest-asyncio==1.2.0",
  "pytest-cov==7.0.0",
  "pytest-icdiff==0.9",
  "pytest-instafail==0.5.0",
  "pytest-mock==3.15.1",
  "pytest-runner==6.0.1",
  "pytest-sugar==1.1.1",
  "pytest-xdist==3.8.0",
  "pytest==8.4.2",
  "python-dateutil==2.9.0.post0",
  "python-dotenv==1.1.1",
  "pyyaml==6.0.3",
  "referencing==0.35.1",
  "regex==2025.11.3",
  "requests==2.32.5",
  "responses==0.25.8",
  "rfc3339-validator==0.1.4",
  "rpds-py==0.28.0",
  "s3transfer==0.13.1",
  "setuptools==80.9.0",
  "six==1.17.0",
  "sqlalchemy2-stubs==0.0.2a38",
  "sqlalchemy==1.4.54",
  "sympy==1.14.0",
  "termcolor==3.1.0",
  "types-aiobotocore-s3==2.25.0",
  "types-aiobotocore==2.25.0",
  "types-aiofiles==24.1.0.20250822",
  "types-awscrt==0.27.6",
  "types-requests==2.32.4.20250913",
  "types-tqdm==4.67.0.20250809",
  "typing-extensions==4.15.0",
  "typing-inspection==0.4.2",
  "tzdata==2025.2",
  "urllib3==2.6.3",
  "werkzeug==3.1.3",
  "wrapt==1.17.3",
  "xmltodict==1.0.2",
  "yarl==1.20.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["simcore_sdk"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
