version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - pcrespov
      - sanderegg
    assignees:
      - pcrespov
    ignore:
      - dependency-name: aiozipkin
        versions:
          - ">= 1.a, < 2"
      - dependency-name: docker-compose
        versions:
          - 1.28.2
          - 1.28.4
          - 1.28.5
          - 1.28.6
          - 1.29.0
          - 1.29.1
      - dependency-name: idna
        versions:
          - "3.1"
      - dependency-name: httpx
        versions:
          - 0.17.0
      - dependency-name: minio
        versions:
          - 7.0.0
  - package-ecosystem: pip
    directory: "/packages/service-library"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - pcrespov
      - sanderegg
    assignees:
      - pcrespov
    ignore:
      - dependency-name: aiozipkin
        versions:
          - ">= 1.a, < 2"
      - dependency-name: openapi-core
        versions:
          - "> 0.12.0, < 1"
  - package-ecosystem: pip
    directory: "/packages/postgres-database"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - pcrespov
      - sanderegg
    assignees:
      - pcrespov
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    reviewers:
      - sanderegg
      - pcrespov
    assignees:
      - sanderegg
