paths:
  /:
    get:
      tags:
        - maintenance
      summary: readiness probe for
      operationId: healthcheck_readiness_probe
      responses:
        "200":
          description: Service information
          content:
            application/json:
              schema:
                $ref: "./components/schemas/health_check.yaml#/HealthCheckEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
  /health:
    get:
      tags:
        - maintenance
      summary: liveliness probe
      operationId: healthcheck_liveness_probe
      responses:
        "200":
          description: Service information
          content:
            application/json:
              schema:
                $ref: "./components/schemas/health_check.yaml#/HealthCheckEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /status:
    get:
      tags:
        - maintenance
      summary: checks status of self and connected services
      operationId: get_app_status
      responses:
        "200":
          description: returns app status check

  /status/diagnostics:
    get:
      tags:
        - maintenance
      operationId: get_app_diagnostics
      responses:
        "200":
          description: returns app diagnostics report

  /status/{service_name}:
    get:
      tags:
        - maintenance
      operationId: get_service_status
      parameters:
        - in: path
          required: true
          name: service_name
          schema:
            type: string
      responses:
        "200":
          description: returns status of connected service

  /config:
    get:
      summary: Front end runtime configuration
      operationId: get_config
      tags:
        - configuration
      responses:
        "200":
          description: configuration details
          content:
            application/json:
              schema:
                $ref: "./components/schemas/config.yaml#/ConfigEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /scheduled_maintenance:
    get:
      tags:
        - maintenance
      summary: Get Scheduled Maintenance
      operationId: get_scheduled_maintenance
      responses:
        "200":
          description: Maintenance scheduled
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledMaintenance"
        "204":
          description: No maintenance scheduled
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

components:
  responses:
    DefaultErrorResponse:
      $ref: "./openapi.yaml#/components/responses/DefaultErrorResponse"
  schemas:
    ScheduledMaintenance:
      title: ScheduledMaintenance
      type: object
      properties:
        start:
          title: Start
          type: string
          description: At what time the Maintenance starts (UTC)
        end:
          title: End
          type: string
          description: At what time the Maintenance end (UTC)
        reason:
          title: Reason
          type: string
          description: What the purpose of the Maintenance is
      additionalProperties: false
