paths:
  /groups:
    get:
      summary: List my groups
      operationId: list_groups
      tags:
        - group
      responses:
        "200":
          description: list of the groups I belonged to
          content:
            application/json:
              schema:
                $ref: "./components/schemas/group.yaml#/AllUsersGroupsEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    post:
      summary: Create a new group
      operationId: create_group
      tags:
        - group
      requestBody:
        required: true
        description: the group to create
        content:
          application/json:
            schema:
              $ref: "./components/schemas/group.yaml#/UsersGroup"
      responses:
        "201":
          description: group created
          content:
            application/json:
              schema:
                $ref: "./components/schemas/group.yaml#/UsersGroupEnveloped"

        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /groups/{gid}:
    parameters:
      - name: gid
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - group
      summary: Gets one group details
      operationId: get_group
      responses:
        "200":
          description: got group
          content:
            application/json:
              schema:
                $ref: "./components/schemas/group.yaml#/UsersGroupEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    patch:
      summary: Update one group
      operationId: update_group
      tags:
        - group
      requestBody:
        required: true
        description: the group to update
        content:
          application/json:
            schema:
              $ref: "./components/schemas/group.yaml#/UsersGroup"
      responses:
        "200":
          description: the modified group
          content:
            application/json:
              schema:
                $ref: "./components/schemas/group.yaml#/UsersGroupEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    delete:
      tags:
        - group
      summary: Deletes one group
      operationId: delete_group
      responses:
        "204":
          description: group has been successfully deleted
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /groups/{gid}/users:
    parameters:
      - name: gid
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - group
      summary: Gets list of users in group
      operationId: get_group_users
      responses:
        "200":
          description: got list of users and their respective rights
          content:
            application/json:
              schema:
                $ref: "./components/schemas/group.yaml#/GroupUsersArrayEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    post:
      tags:
        - group
      summary: Adds a user in the group
      operationId: add_group_user
      requestBody:
        required: true
        description: the user to add
        content:
          application/json:
            schema:
              anyOf:
                - type: object
                  required:
                    - uid
                  properties:
                    uid:
                      type: string
                      description: the user id
                - type: object
                  required:
                    - email
                  properties:
                    email:
                      type: string
                      format: email
                      description: the user email
      responses:
        "204":
          description: user successfully added
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /groups/{gid}/users/{uid}:
    parameters:
      - name: gid
        in: path
        required: true
        schema:
          type: string
      - name: uid
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - group
      summary: Gets specific user in group
      operationId: get_group_user
      responses:
        "200":
          description: got user
          content:
            application/json:
              schema:
                $ref: "./components/schemas/group.yaml#/GroupUserEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    patch:
      tags:
        - group
      summary: Modify specific user in group
      operationId: update_group_user
      requestBody:
        required: true
        description: the user rights to modify
        content:
          application/json:
            schema:
              type: object
              properties:
                accessRights:
                  $ref: "./components/schemas/group.yaml#/GroupAccessRights"
              required:
                - accessRights



      responses:
        "200":
          description: modified user
          content:
            application/json:
              schema:
                $ref: "./components/schemas/group.yaml#/GroupUserEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    delete:
      tags:
        - group
      summary: Delete specific user in group
      operationId: delete_group_user
      responses:
        "204":
          description: successfully removed user
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /groups/{gid}/classifiers:
    get:
      parameters:
        - name: gid
          in: path
          required: true
          schema:
            type: string
        - name: tree_view
          in: query
          description: "Some classifiers (e.g. sparc's) offer different tree views"
          schema:
            type: string
            enum: [std, sort]
            default: std
      tags:
        - group
      summary: Gets classifiers bundle for this group
      operationId: get_group_classifiers
      responses:
        "200":
          description: got a bundle with all information about classifiers
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /groups/sparc/classifiers/scicrunch-resources/{rrid}:
    parameters:
      - name: rrid
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - group
      summary: "Returns information on a valid RRID (https://www.force11.org/group/resource-identification-initiative)"
      operationId: get_scicrunch_resource
      responses:
        "200":
          description: Got information of a valid RRID
        "404":
          description: Cannot find a valid research resource for the provided RRID
        "503":
          description: Underline validation service is not reachable
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    post:
      tags:
        - group
      summary: "Adds new RRID to classifiers"
      operationId: add_scicrunch_resource
      responses:
        "200":
          description: Got information of a valid RRID
        "422":
          description: Invalid RRID
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /groups/sparc/classifiers/scicrunch-resources:search:
     get:
      parameters:
        - name: resource_name_as
          in: query
          required: true
          schema:
            type: string
      tags:
        - group
      summary: "Returns a list of related resource provided a search name"
      operationId: search_scicrunch_resources
      responses:
        "200":
          description: Got information of a valid RRID
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
components:
  responses:
    DefaultErrorResponse:
      $ref: "./openapi.yaml#/components/responses/DefaultErrorResponse"
