paths:
  /activity/status:
    get:
      operationId: get_status
      responses:
        '200':
          description: Object containing queuing, CPU and Memory usage/limits information of services
          content:
            application/json:
              schema:
                $ref: './components/schemas/activity.yaml#/ActivityEnveloped'
        default:
          $ref: './openapi.yaml#/components/responses/DefaultErrorResponse'
