paths:
  /projects/{project_id}/inputs:
    get:
      tags:
      - project
      summary: Get Project Inputs
      description: New in version *0.10*
      operationId: get_project_inputs
      parameters:
      - required: true
        schema:
          title: Project Id
          type: string
          format: uuid
        name: project_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_dict_uuid.UUID__simcore_service_webserver.projects._ports_handlers.ProjectInputGet__'
    patch:
      tags:
      - project
      summary: Update Project Inputs
      description: New in version *0.10*
      operationId: update_project_inputs
      parameters:
      - required: true
        schema:
          title: Project Id
          type: string
          format: uuid
        name: project_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              title: Updates
              type: array
              items:
                $ref: '#/components/schemas/ProjectInputUpdate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_dict_uuid.UUID__simcore_service_webserver.projects._ports_handlers.ProjectInputGet__'
  /projects/{project_id}/outputs:
    get:
      tags:
      - project
      summary: Get Project Outputs
      description: New in version *0.10*
      operationId: get_project_outputs
      parameters:
      - required: true
        schema:
          title: Project Id
          type: string
          format: uuid
        name: project_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_dict_uuid.UUID__simcore_service_webserver.projects._ports_handlers.ProjectOutputGet__'
  /projects/{project_id}/metadata/ports:
    get:
      tags:
      - project
      summary: List Project Metadata Ports
      description: New in version *0.12*
      operationId: list_project_metadata_ports
      parameters:
      - required: true
        schema:
          title: Project Id
          type: string
          format: uuid
        name: project_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_list_simcore_service_webserver.projects._ports_handlers.ProjectMetadataPortGet__'
components:
  schemas:
    Envelope_dict_uuid.UUID__simcore_service_webserver.projects._ports_handlers.ProjectInputGet__:
      title: Envelope[dict[uuid.UUID, simcore_service_webserver.projects._ports_handlers.ProjectInputGet]]
      type: object
      properties:
        data:
          title: Data
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ProjectInputGet'
        error:
          title: Error
    Envelope_dict_uuid.UUID__simcore_service_webserver.projects._ports_handlers.ProjectOutputGet__:
      title: Envelope[dict[uuid.UUID, simcore_service_webserver.projects._ports_handlers.ProjectOutputGet]]
      type: object
      properties:
        data:
          title: Data
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ProjectOutputGet'
        error:
          title: Error
    Envelope_list_simcore_service_webserver.projects._ports_handlers.ProjectMetadataPortGet__:
      title: Envelope[list[simcore_service_webserver.projects._ports_handlers.ProjectMetadataPortGet]]
      type: object
      properties:
        data:
          title: Data
          type: array
          items:
            $ref: '#/components/schemas/ProjectMetadataPortGet'
        error:
          title: Error
    ProjectInputGet:
      title: ProjectInputGet
      required:
      - key
      - value
      - label
      type: object
      properties:
        key:
          title: Key
          type: string
          description: Project port's unique identifer. Same as the UUID of the associated
            port node
          format: uuid
        value:
          title: Value
          description: Value assigned to this i/o port
        label:
          title: Label
          type: string
    ProjectInputUpdate:
      title: ProjectInputUpdate
      required:
      - key
      - value
      type: object
      properties:
        key:
          title: Key
          type: string
          description: Project port's unique identifer. Same as the UUID of the associated
            port node
          format: uuid
        value:
          title: Value
          description: Value assigned to this i/o port
    ProjectMetadataPortGet:
      title: ProjectMetadataPortGet
      required:
      - key
      - kind
      type: object
      properties:
        key:
          title: Key
          type: string
          description: Project port's unique identifer. Same as the UUID of the associated
            port node
          format: uuid
        kind:
          title: Kind
          enum:
          - input
          - output
          type: string
        content_schema:
          title: Content Schema
          type: object
          description: jsonschema for the port's value. SEE https://json-schema.org/understanding-json-schema/
    ProjectOutputGet:
      title: ProjectOutputGet
      required:
      - key
      - value
      - label
      type: object
      properties:
        key:
          title: Key
          type: string
          description: Project port's unique identifer. Same as the UUID of the associated
            port node
          format: uuid
        value:
          title: Value
          description: Value assigned to this i/o port
        label:
          title: Label
          type: string
