paths:
  /tasks:
    get:
      operationId: list_tasks
      tags:
        - tasks
      responses:
        "200":
          description: Lists all the tasks currently available/running
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas/task.yaml#/TaskEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /tasks/{task_id}:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: get_task_status
      tags:
        - tasks
      responses:
        "200":
          description: Returns the task status
          content:
            application/json:
              schema:
                $ref: "./components/schemas/task.yaml#/TaskStatusEnveloped"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    delete:
      operationId: cancel_and_delete_task
      description: Aborts and remove the task
      tags:
        - tasks
      responses:
        "204":
          description: Task was successfully aborted
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /tasks/{task_id}/result:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: get_task_result
      tags:
        - tasks
      responses:
        "2XX":
          description: Retrieve the task result and returns directly its HTTP code
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

components:
  responses:
    DefaultErrorResponse:
      $ref: "./openapi.yaml#/components/responses/DefaultErrorResponse"
