paths:
  /repos/projects:
    get:
      tags:
        - repository
      summary: List Repos
      description: List info about versioned projects
      operationId: simcore_service_webserver.version_control_handlers._list_repos_handler
      parameters:
        - description: index to the first item to return (pagination)
          required: false
          schema:
            title: Offset
            exclusiveMinimum: false
            type: integer
            description: index to the first item to return (pagination)
            default: 0
          name: offset
          in: query
        - description: maximum number of items to return (pagination)
          required: false
          schema:
            title: Limit
            maximum: 50
            minimum: 1
            type: integer
            description: maximum number of items to return (pagination)
            default: 20
          name: limit
          in: query
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Page_Repo_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /repos/projects/{project_uuid}/checkpoints:
    get:
      tags:
        - repository
      summary: List Checkpoints
      description: Lists commits&tags tree of the project
      operationId: simcore_service_webserver.version_control_handlers._list_checkpoints_handler
      parameters:
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
        - description: index to the first item to return (pagination)
          required: false
          schema:
            title: Offset
            exclusiveMinimum: false
            type: integer
            description: index to the first item to return (pagination)
            default: 0
          name: offset
          in: query
        - description: maximum number of items to return (pagination)
          required: false
          schema:
            title: Limit
            maximum: 50
            minimum: 1
            type: integer
            description: maximum number of items to return (pagination)
            default: 20
          name: limit
          in: query
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Page_Checkpoint_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
    post:
      tags:
        - repository
      summary: Create Checkpoint
      operationId: simcore_service_webserver.version_control_handlers._create_checkpoint_handler
      parameters:
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckpointNew"
        required: true
      responses:
        "201":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Envelope_Checkpoint_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /repos/projects/{project_uuid}/checkpoints/{ref_id}:
    get:
      tags:
        - repository
      summary: Get Checkpoint
      description: Set ref_id=HEAD to return current commit
      operationId: simcore_service_webserver.version_control_handlers._get_checkpoint_handler
      parameters:
        - description: A repository ref (commit, tag or branch)
          required: true
          schema:
            title: Ref Id
            anyOf:
              - type: string
                format: uuid
              - type: string
            description: A repository ref (commit, tag or branch)
          name: ref_id
          in: path
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Envelope_Checkpoint_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
    patch:
      tags:
        - repository
      summary: Update Checkpoint Annotations
      operationId: simcore_service_webserver.version_control_handlers._update_checkpoint_annotations_handler
      parameters:
        - description: A repository ref (commit, tag or branch)
          required: true
          schema:
            title: Ref Id
            anyOf:
              - type: string
                format: uuid
              - type: string
            description: A repository ref (commit, tag or branch)
          name: ref_id
          in: path
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckpointAnnotations"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Envelope_Checkpoint_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /repos/projects/{project_uuid}/checkpoints/{ref_id}:checkout:
    post:
      tags:
        - repository
      summary: Checkout
      description: |-
        Affect current working copy of the project, i.e. get_project will now return
        the check out
      operationId: simcore_service_webserver.version_control_handlers._checkout_handler
      parameters:
        - description: A repository ref (commit, tag or branch)
          required: true
          schema:
            title: Ref Id
            anyOf:
              - type: string
                format: uuid
              - type: string
            description: A repository ref (commit, tag or branch)
          name: ref_id
          in: path
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Envelope_Checkpoint_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /repos/projects/{project_uuid}/checkpoints/{ref_id}/workbench/view:
    get:
      tags:
        - repository
      summary: View Project Workbench
      description: Returns a view of the workbench for a given project's version
      operationId: simcore_service_webserver.version_control_handlers._view_project_workbench_handler
      parameters:
        - description: A repository ref (commit, tag or branch)
          required: true
          schema:
            title: Ref Id
            anyOf:
              - type: string
                format: uuid
              - type: string
            description: A repository ref (commit, tag or branch)
          name: ref_id
          in: path
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Envelope_WorkbenchView_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    Checkpoint:
      title: Checkpoint
      required:
        - id
        - checksum
        - tag
        - message
        - parent
        - created_at
        - url
      type: object
      properties:
        id:
          title: Id
          exclusiveMinimum: false
          type: integer
        checksum:
          title: Checksum
          type: string
        tag:
          title: Tag
          type: string
        message:
          title: Message
          type: string
        parent:
          title: Parent
          exclusiveMinimum: false
          type: integer
        created_at:
          title: Created At
          type: string
          format: date-time
        url:
          title: Url
          maxLength: 2083
          minLength: 1
          type: string
          format: uri
    CheckpointAnnotations:
      title: CheckpointAnnotations
      type: object
      properties:
        tag:
          title: Tag
          type: string
        message:
          title: Message
          type: string
    CheckpointNew:
      title: CheckpointNew
      required:
        - tag
      type: object
      properties:
        tag:
          title: Tag
          type: string
        message:
          title: Message
          type: string
    Envelope_Checkpoint_:
      title: Envelope[Checkpoint]
      type: object
      properties:
        data:
          $ref: "#/components/schemas/Checkpoint"
        error:
          $ref: "#/components/schemas/Error"
    Envelope_WorkbenchView_:
      title: Envelope[WorkbenchView]
      type: object
      properties:
        data:
          $ref: "#/components/schemas/WorkbenchView"
        error:
          $ref: "#/components/schemas/Error"
    Error:
      title: Error
      required:
        - code
        - message
      type: object
      properties:
        code:
          title: Code
          type: integer
        message:
          title: Message
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    Node:
      title: Node
      required:
        - key
        - version
        - label
        - inputs
        - outputs
      type: object
      properties:
        key:
          title: Key
          type: string
        version:
          title: Version
          pattern: \d+\.\d+\.\d+
          type: string
        label:
          title: Label
          type: string
        inputs:
          title: Inputs
          type: object
        outputs:
          title: Outputs
          type: object
    PageLinks:
      title: PageLinks
      required:
        - self
        - first
        - last
      type: object
      properties:
        self:
          title: Self
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        first:
          title: First
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        prev:
          title: Prev
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        next:
          title: Next
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        last:
          title: Last
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
      additionalProperties: false
    PageMetaInfoLimitOffset:
      title: PageMetaInfoLimitOffset
      required:
        - limit
        - total
        - count
      type: object
      properties:
        limit:
          title: Limit
          exclusiveMinimum: false
          type: integer
        total:
          title: Total
          minimum: 0
          type: integer
        offset:
          title: Offset
          minimum: 0
          type: integer
          default: 0
        count:
          title: Count
          minimum: 0
          type: integer
      additionalProperties: false
    Page_Checkpoint_:
      title: Page[Checkpoint]
      required:
        - _meta
        - _links
        - data
      type: object
      properties:
        _meta:
          $ref: "#/components/schemas/PageMetaInfoLimitOffset"
        _links:
          $ref: "#/components/schemas/PageLinks"
        data:
          title: Data
          type: array
          items:
            $ref: "#/components/schemas/Checkpoint"
    Page_Repo_:
      title: Page[Repo]
      required:
        - _meta
        - _links
        - data
      type: object
      properties:
        _meta:
          $ref: "#/components/schemas/PageMetaInfoLimitOffset"
        _links:
          $ref: "#/components/schemas/PageLinks"
        data:
          title: Data
          type: array
          items:
            $ref: "#/components/schemas/Repo"
    Repo:
      title: Repo
      required:
        - project_uuid
        - url
      type: object
      properties:
        project_uuid:
          title: Project Uuid
          type: string
          format: uuid
        url:
          title: Url
          maxLength: 2083
          minLength: 1
          type: string
          format: uri
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    WorkbenchView:
      title: WorkbenchView
      type: object
      properties:
        workbench:
          title: Workbench
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Node"
          default: {}
        ui:
          title: Ui
          type: object
          default: {}
      description: A view (i.e. read-only and visual) of the project's workbench
