paths:
  /projects/{project_uuid}/checkpoint/{ref_id}/iterations:
    get:
      tags:
        - meta-projects
      summary: List Project Iterations
      description: Lists current project's iterations
      operationId: "simcore_service_webserver.meta_handlers._list_meta_project_iterations_handler"
      parameters:
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
        - required: true
          schema:
            title: Ref Id
            anyOf:
              - type: integer
              - type: string
          name: ref_id
          in: path
        - description: index to the first item to return (pagination)
          required: false
          schema:
            title: Offset
            exclusiveMinimum: false
            type: integer
            description: index to the first item to return (pagination)
            default: 0
            minimum: 0
          name: offset
          in: query
        - description: maximum number of items to return (pagination)
          required: false
          schema:
            title: Limit
            maximum: 50.0
            minimum: 1.0
            type: integer
            description: maximum number of items to return (pagination)
            default: 20
          name: limit
          in: query
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Page_IterationAsItem_"
        "404":
          description:
            This project has no iterations.Only meta-project have iterations
            and they must be explicitly created.
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
    post:
      tags:
        - meta-projects
      summary: Create Project Iterations
      description: "Gets or creates projects iterations

        If the number of iterations is not bound (e.g. in an optimization) then it responds
        when the requested range (offset: offset+limits)
        "
      operationId: "simcore_service_webserver.meta_handlers._create_meta_project_iterations_handler"
      parameters:
        - description: Project unique identifier
          required: true
          schema:
            title: Project Uuid
            type: string
            description: Project unique identifier
            format: uuid
          name: project_uuid
          in: path
        - required: true
          schema:
            title: Ref Id
            anyOf:
              - type: integer
              - type: string
          name: ref_id
          in: path
        - description: index to the first item to return (pagination)
          required: false
          schema:
            title: Offset
            exclusiveMinimum: false
            type: integer
            description: index to the first item to return (pagination)
            default: 0
            minimum: 0
          name: offset
          in: query
        - description: maximum number of items to return (pagination)
          required: false
          schema:
            title: Limit
            maximum: 50.0
            minimum: 1.0
            type: integer
            description: maximum number of items to return (pagination)
            default: 20
          name: limit
          in: query
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Page_IterationAsItem_"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    IterationAsItem:
      title: IterationAsItem
      required:
        - name
        - parent
        - workcopy_project_id
        - workcopy_project_url
        - url
      type: object
      properties:
        name:
          title: Name
          type: string
          description: Iteration's resource name [AIP-122](https://google.aip.dev/122)
        parent:
          title: Parent
          allOf:
            - $ref: "#/components/schemas/ParentMetaProjectRef"
          description: Reference to the the meta-project that defines this iteration
        workcopy_project_id:
          title: Workcopy's Project Id
          type: string
          description:
            ID to this iteration's working copy.A working copy is a real
            project where this iteration is run
          format: uuid
        workcopy_project_url:
          title: Workcopy's Project Url
          maxLength: 2083
          minLength: 1
          type: string
          format: uri
        url:
          title: Url
          maxLength: 2083
          minLength: 1
          type: string
          format: uri
    PageLinks:
      title: PageLinks
      required:
        - self
        - first
        - last
      type: object
      properties:
        self:
          title: Self
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        first:
          title: First
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        prev:
          title: Prev
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        next:
          title: Next
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
        last:
          title: Last
          maxLength: 65536
          minLength: 1
          type: string
          format: uri
      additionalProperties: false
    PageMetaInfoLimitOffset:
      title: PageMetaInfoLimitOffset
      required:
        - total
        - count
      type: object
      properties:
        limit:
          title: Limit
          exclusiveMinimum: true
          type: integer
          default: 20
          minimum: 0
        total:
          title: Total
          minimum: 0.0
          type: integer
        offset:
          title: Offset
          minimum: 0.0
          type: integer
          default: 0
        count:
          title: Count
          minimum: 0.0
          type: integer
    Page_IterationAsItem_:
      title: Page[IterationAsItem]
      required:
        - _meta
        - _links
        - data
      type: object
      properties:
        _meta:
          $ref: "#/components/schemas/PageMetaInfoLimitOffset"
        _links:
          $ref: "#/components/schemas/PageLinks"
        data:
          title: Data
          type: array
          items:
            $ref: "#/components/schemas/IterationAsItem"
    ParentMetaProjectRef:
      title: ParentMetaProjectRef
      required:
        - project_id
        - ref_id
      type: object
      properties:
        project_id:
          title: Project Id
          type: string
          format: uuid
        ref_id:
          title: Ref Id
          type: integer
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
