paths:
  /wallets:
    get:
      tags:
      - wallets
      summary: List Wallets
      operationId: list_wallets
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_list_models_library.wallets.WalletGet__'
    post:
      tags:
      - wallets
      summary: Create Wallet
      operationId: create_wallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_CreateWalletBodyParams'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_WalletGet_'
  /wallets/{wallet_id}:
    put:
      tags:
      - wallets
      summary: Update Wallet
      operationId: update_wallet
      parameters:
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Wallet Id
          minimum: 0
        name: wallet_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_PutWalletBodyParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_WalletGet_'
  /wallets/{wallet_id}/groups/{group_id}:
    put:
      tags:
      - wallets
      summary: Update Wallet Group
      operationId: update_wallet_group
      parameters:
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Wallet Id
          minimum: 0
        name: wallet_id
        in: path
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Group Id
          minimum: 0
        name: group_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_WalletsGroupsParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_WalletGroupGet_'
    post:
      tags:
      - wallets
      summary: Create Wallet Group
      operationId: create_wallet_group
      parameters:
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Wallet Id
          minimum: 0
        name: wallet_id
        in: path
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Group Id
          minimum: 0
        name: group_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_WalletsGroupsParams'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_WalletGroupGet_'
    delete:
      tags:
      - wallets
      summary: Delete Wallet Group
      operationId: delete_wallet_group
      parameters:
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Wallet Id
          minimum: 0
        name: wallet_id
        in: path
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Group Id
          minimum: 0
        name: group_id
        in: path
      responses:
        '204':
          description: Successful Response
  /wallets/{wallet_id}/groups:
    get:
      tags:
      - wallets
      summary: List Wallet Groups
      operationId: list_wallet_groups
      parameters:
      - required: true
        schema:
          type: integer
          exclusiveMinimum: true
          title: Wallet Id
          minimum: 0
        name: wallet_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Envelope_list_simcore_service_webserver.wallets._groups_api.WalletGroupGet__'
components:
  schemas:
    Envelope_WalletGet_:
      properties:
        data:
          $ref: '#/components/schemas/WalletGet'
        error:
          title: Error
      type: object
      title: Envelope[WalletGet]
    Envelope_WalletGroupGet_:
      properties:
        data:
          $ref: '#/components/schemas/WalletGroupGet'
        error:
          title: Error
      type: object
      title: Envelope[WalletGroupGet]
    Envelope_list_models_library.wallets.WalletGet__:
      properties:
        data:
          items:
            $ref: '#/components/schemas/WalletGet'
          type: array
          title: Data
        error:
          title: Error
      type: object
      title: Envelope[list[models_library.wallets.WalletGet]]
    Envelope_list_simcore_service_webserver.wallets._groups_api.WalletGroupGet__:
      properties:
        data:
          items:
            $ref: '#/components/schemas/WalletGroupGet'
          type: array
          title: Data
        error:
          title: Error
      type: object
      title: Envelope[list[simcore_service_webserver.wallets._groups_api.WalletGroupGet]]
    WalletGet:
      properties:
        id:
          type: integer
          exclusiveMinimum: true
          title: Id
          minimum: 0
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        owner:
          type: integer
          exclusiveMinimum: true
          title: Owner
          minimum: 0
        thumbnail:
          type: string
          title: Thumbnail
        status:
          $ref: '#/components/schemas/WalletStatus'
        created:
          type: string
          format: date-time
          title: Created
        modified:
          type: string
          format: date-time
          title: Modified
      type: object
      required:
      - id
      - name
      - description
      - owner
      - thumbnail
      - status
      - created
      - modified
      title: WalletGet
    WalletGroupGet:
      properties:
        gid:
          type: integer
          exclusiveMinimum: true
          title: Gid
          minimum: 0
        read:
          type: boolean
          title: Read
        write:
          type: boolean
          title: Write
        delete:
          type: boolean
          title: Delete
        created:
          type: string
          format: date-time
          title: Created
        modified:
          type: string
          format: date-time
          title: Modified
      type: object
      required:
      - gid
      - read
      - write
      - delete
      - created
      - modified
      title: WalletGroupGet
    WalletStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      title: WalletStatus
      description: An enumeration.
    _CreateWalletBodyParams:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        thumbnail:
          type: string
          title: Thumbnail
      additionalProperties: false
      type: object
      required:
      - name
      title: _CreateWalletBodyParams
    _PutWalletBodyParams:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        thumbnail:
          type: string
          title: Thumbnail
        status:
          $ref: '#/components/schemas/WalletStatus'
      additionalProperties: false
      type: object
      required:
      - name
      - description
      - thumbnail
      - status
      title: _PutWalletBodyParams
    _WalletsGroupsParams:
      properties:
        read:
          type: boolean
          title: Read
        write:
          type: boolean
          title: Write
        delete:
          type: boolean
          title: Delete
      additionalProperties: false
      type: object
      required:
      - read
      - write
      - delete
      title: _WalletsGroupsParams
