[project]
name = "simcore-postgres-database"
version = "0.11.0"
description = "Core service library for simcore"
readme = "README.md"
requires-python = "~=3.13.0"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "simcore-common-library",
  "alembic",
  "pydantic>=2.10.0,<2.12.0",
  "sqlalchemy[postgresql_psycopg2binary,postgresql_asyncpg]>=1.3.3,<2.0",
  "yarl",
]

[project.optional-dependencies]
test = [
  "aiopg==1.4.0",
  "arrow==1.3.0",
  "async-timeout==4.0.3",
  "attrs==25.3.0",
  "coverage==7.10.7",
  "faker==37.8.0",
  "greenlet==3.2.4",
  "iniconfig==2.1.0",
  "mypy-extensions==1.1.0",
  "mypy==1.18.2",
  "packaging==25.0",
  "pathspec==0.12.1",
  "pluggy==1.6.0",
  "psycopg2-binary==2.9.11",
  "pygments==2.19.2",
  "pytest-asyncio==1.2.0",
  "pytest-cov==7.0.0",
  "pytest-docker==3.2.3",
  "pytest-instafail==0.5.0",
  "pytest-runner==6.0.1",
  "pytest==8.4.2",
  "python-dateutil==2.9.0.post0",
  "pyyaml==6.0.3",
  "six==1.17.0",
  "sqlalchemy2-stubs==0.0.2a38",
  "sqlalchemy==1.4.54",
  "types-docker==7.1.0.20250916",
  "types-psycopg2==2.9.21.20250915",
  "types-python-dateutil==2.9.0.20250822",
  "types-requests==2.32.4.20250913",
  "typing-extensions==4.15.0",
  "tzdata==2025.2",
  "urllib3==2.6.3",
]
migration = [
  "alembic>=1.0,<2.0",
  "click>=8.0,<9.0",
  "docker>=6.0,<8.0",
  "tenacity>=8.0,<9.0",
  "urllib3>=2.0,<3.0",
]

[project.scripts]
simcore-service-postgres-database = "simcore_postgres_database.cli:main"
sc-pg = "simcore_postgres_database.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["simcore_postgres_database"]
include-package-data = true

[tool.setuptools.package-data]
"*" = [
  "py.typed",
  "*.ini",
  "migration/*.py",
  "migration/*.mako",
  "migration/versions/*.py",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
