[project]
name = "simcore-postgres-database"
version = "0.11.0"
description = "Core service library for simcore"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "alembic>=1.16.5",
  "click>=8.3.0",
  "docker>=7.1.0",
  "orjson>=3.11.4",
  "pydantic>=2.11.9",
  "pydantic-extra-types>=2.10.5",
  "simcore-common-library",
  "sqlalchemy[postgresql-asyncpg,postgresql-psycopg2binary]>=1.4.54",
  "tenacity>=9.1.2",
  "urllib3>=2.6.3",
  "yarl>=1.20.1",
]


[project.scripts]
simcore-service-postgres-database = "simcore_postgres_database.cli:main"
sc-pg = "simcore_postgres_database.cli:main"


[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["simcore_postgres_database"]
include-package-data = true

[tool.setuptools.package-data]
"*" = [
  "py.typed",
  "*.ini",
  "migration/*.py",
  "migration/*.mako",
  "migration/versions/*.py",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]

[tool.uv.sources]
pytest-simcore = { path = "../pytest-simcore", editable = true }
simcore-common-library = { path = "../common-library", editable = true }

[dependency-groups]
dev = [
  "aiopg[sa]>=1.4.0",
  "arrow>=1.3.0",
  "coverage>=7.10.7",
  "faker>=37.8.0",
  "mypy>=1.18.2",
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
  "pytest-cov>=7.0.0",
  "pytest-docker>=3.2.3",
  "pytest-instafail>=0.5.0",
  "pytest-runner>=6.0.1",
  "pytest-simcore",
  "pyyaml>=6.0.3",
  "sqlalchemy[mypy]>=1.4.54",
  "types-docker>=7.1.0.20250916",
  "types-psycopg2>=2.9.21.20250915",
]
devtools = [
  "black>=25.9.0",
  "bump2version>=1.0.1",
  "isort>=6.1.0",
  "mypy>=1.18.2",
  "pre-commit>=4.3.0",
  "pylint>=3.3.8",
  "ruff>=0.13.3",
]
