[project]
name = "simcore-models-library"
version = "0.3.0"
description = "Core service library for simcore pydantic models"
readme = "README.md"
requires-python = "~=3.13.0"
authors = [{ name = "Sylvain Anderegg", email = "support@osparc.io" }]
license = { text = "MIT" }
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "simcore-common-library",
  "arrow",
  "jsonref",
  "jsonschema",
  "orjson>=3.9.15",
  "pydantic-extra-types",
  "pydantic-settings<2.7.1",
  "pydantic[email]>=2.10.0,<2.12.0",
]

[project.optional-dependencies]
test = [
  "attrs==25.3.0",
  "coverage==7.10.7",
  "faker==37.8.0",
  "flexcache==0.3",
  "flexparser==0.4",
  "icdiff==2.0.7",
  "idna==3.10",
  "iniconfig==2.1.0",
  "multidict==6.6.4",
  "packaging==25.0",
  "pint==0.25",
  "platformdirs==4.4.0",
  "pluggy==1.6.0",
  "pprintpp==0.4.0",
  "propcache==0.3.2",
  "psutil==7.1.0",
  "pygments==2.19.2",
  "pytest==8.4.2",
  "pytest-asyncio==1.2.0",
  "pytest-cov==7.0.0",
  "pytest-icdiff==0.9",
  "pytest-instafail==0.5.0",
  "pytest-mock==3.15.1",
  "pytest-runner==6.0.1",
  "pytest-sugar==1.1.1",
  "python-dotenv==1.1.1",
  "pyyaml==6.0.3",
  "referencing==0.35.1",
  "rpds-py==0.28.0",
  "termcolor==3.1.0",
  "types-jsonschema==4.25.1.20250822",
  "types-pyyaml==6.0.12.20250915",
  "typing-extensions==4.15.0",
  "tzdata==2025.2",
  "yarl==1.20.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["models_library"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
