[project]
name = "simcore-aws-library"
version = "0.1.0"
description = "Core service library for simcore AWS support"
readme = "README.md"
requires-python = "~=3.13.0"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "simcore-common-library",
  "simcore-models-library",
  "simcore-service-library",
  "simcore-settings-library",
  "aioboto3",
  "aiocache",
  "arrow",
  "certifi>=2023.7.22",
  "pydantic[email]>=2.10.0,<2.12.0",
  "types-aiobotocore[ec2,s3,ssm]",
  "opentelemetry-instrumentation-botocore",
  "sh",
]

[project.optional-dependencies]
test = [
  "annotated-types==0.7.0",
  "antlr4-python3-runtime==4.13.2",
  "anyio==4.11.0",
  "attrs==25.3.0",
  "aws-sam-translator==1.100.0",
  "aws-xray-sdk==2.14.0",
  "blinker==1.9.0",
  "boto3==1.39.11",
  "botocore-stubs==1.40.33",
  "botocore==1.39.11",
  "certifi==2025.8.3",
  "cffi==2.0.0",
  "cfn-lint==1.40.0",
  "charset-normalizer==3.4.3",
  "click==8.3.0",
  "coverage==7.10.7",
  "cryptography==46.0.2",
  "docker==7.1.0",
  "faker==37.8.0",
  "fastapi==0.118.0",
  "flask-cors==6.0.1",
  "flask==3.1.2",
  "flexcache==0.3",
  "flexparser==0.4",
  "graphql-core==3.2.6",
  "h11==0.16.0",
  "httpcore==1.0.9",
  "httpx==0.28.1",
  "icdiff==2.0.7",
  "idna==3.10",
  "iniconfig==2.1.0",
  "itsdangerous==2.2.0",
  "jinja2==3.1.6",
  "jmespath==1.0.1",
  "joserfc==1.3.4",
  "jsonpatch==1.33",
  "jsonpath-ng==1.7.0",
  "jsonpointer==3.0.0",
  "jsonschema-path==0.3.4",
  "jsonschema-specifications==2025.9.1",
  "jsonschema==4.25.1",
  "lazy-object-proxy==1.12.0",
  "markupsafe==3.0.3",
  "moto==5.1.13",
  "mpmath==1.3.0",
  "networkx==3.5",
  "openapi-schema-validator==0.6.3",
  "openapi-spec-validator==0.7.2",
  "packaging==25.0",
  "pathable==0.4.4",
  "pint==0.25",
  "platformdirs==4.4.0",
  "pluggy==1.6.0",
  "ply==3.11",
  "pprintpp==0.4.0",
  "py-cpuinfo==9.0.0",
  "py-partiql-parser==0.6.1",
  "pycparser==2.23",
  "pydantic-core==2.33.2",
  "pydantic==2.11.9",
  "pygments==2.19.2",
  "pyparsing==3.2.5",
  "pytest-asyncio==1.2.0",
  "pytest-benchmark==5.1.0",
  "pytest-cov==7.0.0",
  "pytest-icdiff==0.9",
  "pytest-instafail==0.5.0",
  "pytest-mock==3.15.1",
  "pytest-runner==6.0.1",
  "pytest-sugar==1.1.1",
  "pytest==8.4.2",
  "python-dateutil==2.9.0.post0",
  "python-dotenv==1.1.1",
  "pyyaml==6.0.3",
  "referencing==0.35.1",
  "regex==2025.11.3",
  "requests==2.32.5",
  "responses==0.25.8",
  "rfc3339-validator==0.1.4",
  "rpds-py==0.28.0",
  "s3transfer==0.13.1",
  "setuptools==80.9.0",
  "six==1.17.0",
  "sniffio==1.3.1",
  "starlette==0.48.0",
  "sympy==1.14.0",
  "termcolor==3.1.0",
  "types-aioboto3==15.2.0",
  "types-aiobotocore==2.25.0",
  "types-awscrt==0.27.6",
  "types-boto3==1.40.44",
  "types-s3transfer==0.13.1",
  "typing-extensions==4.15.0",
  "typing-inspection==0.4.2",
  "tzdata==2025.2",
  "urllib3==2.6.3",
  "werkzeug==3.1.3",
  "wrapt==1.17.3",
  "xmltodict==1.0.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["aws_library"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
