[project]
name = "simcore-settings-library"
version = "0.1.0"
description = "Core service library for simcore settings"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "simcore-common-library",
  "pydantic>=2.10.0,<2.12.0",
  "pydantic-settings<2.7.1",
  "rich",
  "typer",
]

[project.optional-dependencies]
test = [
  "coverage==7.10.7",
  "faker==37.8.0",
  "iniconfig==2.1.0",
  "packaging==25.0",
  "pluggy==1.6.0",
  "pygments==2.19.2",
  "pytest-cov==7.0.0",
  "pytest-instafail==0.5.0",
  "pytest-mock==3.15.1",
  "pytest-runner==6.0.1",
  "pytest-sugar==1.1.1",
  "pytest==8.4.2",
  "python-dotenv==1.1.1",
  "termcolor==3.1.0",
  "tzdata==2025.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["settings_library"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
