[project]
name = "simcore-settings-library"
version = "0.1.0"
description = "Core service library for simcore settings"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "orjson>=3.11.4",
  "pydantic>=2.11.9",
  "pydantic-extra-types>=2.10.5",
  "pydantic-settings>=2.7.0",
  "pytest-asyncio>=1.2.0",
  "rich>=14.1.0",
  "simcore-common-library",
  "typer>=0.19.2",
]


[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "settings_library"

[tool.uv.sources]
pytest-simcore = { path = "../pytest-simcore", editable = true }
simcore-common-library = { path = "../common-library", editable = true }


[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]

[dependency-groups]
dev = [
  "coverage>=7.10.7",
  "faker>=37.8.0",
  "mypy>=1.18.2",
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
  "pytest-instafail>=0.5.0",
  "pytest-mock>=3.15.1",
  "pytest-runner>=6.0.1",
  "pytest-simcore",
  "pytest-sugar>=1.1.1",
  "python-dotenv>=1.1.1",
]
devtools = [
  "black>=25.9.0",
  "bump2version>=1.0.1",
  "isort>=6.1.0",
  "mypy>=1.18.2",
  "pre-commit>=4.3.0",
  "pylint>=3.3.8",
  "ruff>=0.13.3",
]
