[project]
name = "simcore-common-library"
version = "0.2.0"
description = "Core service library for simcore pydantic common"
readme = "README.md"
requires-python = "~=3.13.0"
authors = [{ name = "Giancarlo Romeo", email = "support@osparc.io" }]
license = { text = "MIT" }
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
]
dependencies = [
    "orjson>=3.11.4",
    "pydantic>=2.11.9",
    "pydantic-extra-types>=2.10.5",
]


[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "common_library"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["common_library"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
