#
# Build services to a specific target stage and tags them as 'local/{service}:${BUILD_TARGET}'
#
#  - BUILD_TARGET (build_target_required) must be set as 'production', 'development' or 'cache'. Used as image tag
#
# NOTE: linter error 'missing image' happens with the file is called 'docker-compose.build.yml'
#
version: "3.7"
services:
  api-server:
    image: local/api-server:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/api-server/Dockerfile
      cache_from:
        - local/api-server:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/api-server:cache
        - ${DOCKER_REGISTRY:-itisfoundation}/api-server:${DOCKER_IMAGE_TAG:-latest}
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${API_SERVER_API_VERSION}"

  catalog:
    image: local/catalog:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/catalog/Dockerfile
      cache_from:
        - local/catalog:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/catalog:cache
        - ${DOCKER_REGISTRY:-itisfoundation}/catalog:${DOCKER_IMAGE_TAG:-latest}
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${CATALOG_API_VERSION}"

  director:
    image: local/director:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/director/Dockerfile
      cache_from:
        - local/director:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/director:cache
        - ${DOCKER_REGISTRY:-itisfoundation}/director:${DOCKER_IMAGE_TAG:-latest}
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${DIRECTOR_API_VERSION}"

  migration:
    image: local/migration:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/migration/Dockerfile
      target: production
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"

  webserver:
    image: local/webserver:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/web/Dockerfile
      cache_from:
        - local/webserver:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/webserver:cache
        - ${DOCKER_REGISTRY:-itisfoundation}/webserver:${DOCKER_IMAGE_TAG:-latest}
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${WEBSERVER_API_VERSION}"

  sidecar:
    image: local/sidecar:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/sidecar/Dockerfile
      cache_from:
        - local/sidecar:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/sidecar:cache
        - ${DOCKER_REGISTRY:-itisfoundation}/sidecar:${DOCKER_IMAGE_TAG:-latest}
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"

  storage:
    image: local/storage:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/storage/Dockerfile
      cache_from:
        - local/storage:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/storage:cache
        - ${DOCKER_REGISTRY:-itisfoundation}/storage:${DOCKER_IMAGE_TAG:-latest}
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${STORAGE_API_VERSION}"
