x-common-healthchecks: &common-healthchecks
  interval: 30s
  timeout: 10s
  start_period: 60s

services:
  api-server:
    healthcheck:
      <<:
        - *common-healthchecks

  api-worker:
    healthcheck:
      <<:
        - *common-healthchecks

  notifications:
    healthcheck:
      <<:
        - *common-healthchecks

  storage:
    healthcheck:
      <<:
        - *common-healthchecks

  sto-worker:
    healthcheck:
      <<:
        - *common-healthchecks

  sto-worker-cpu-bound:
    healthcheck:
      <<:
        - *common-healthchecks
