x-common-healthchecks: &common-healthchecks
  healthcheck:
    interval: 30s
    timeout: 10s
    start_period: 60s

services:
  api-server:
    <<: *common-healthchecks

  api-worker:
    <<: *common-healthchecks

  catalog:
    <<: *common-healthchecks

  dask-scheduler:
    <<: *common-healthchecks

  dask-sidecar:
    <<: *common-healthchecks

  director-v2:
    <<: *common-healthchecks

  notifications:
    <<: *common-healthchecks

  notifications-wrk:
    <<: *common-healthchecks

  storage:
    <<: *common-healthchecks

  sto-worker:
    <<: *common-healthchecks

  sto-worker-cpu-bound:
    <<: *common-healthchecks

  wb-db-event-listener:
    <<: *common-healthchecks

  wb-garbage-collector:
    <<: *common-healthchecks

  webserver:
    <<: *common-healthchecks
