#
# Build services to a specific target stage and tags them as 'local/{service}:${BUILD_TARGET}'
#
#  - BUILD_TARGET (build_target_required) must be set as 'production', 'development' or 'cache'. Used as image tag
#
# NOTE: linter error 'missing image' happens with the file is called 'docker-compose.build.yml'
#
# NOTE: service-integration is NOT a stack service but an executable of the service-integration library
#
# NOTE: the dask-scheduler uses the same image as the dask-sidecar. there is no need to build it twice!
#
version: "3.8"
services:
  service-integration:
    image: local/service-integration:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: packages/service-integration/Dockerfile
      cache_from:
        - local/service-integration:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/service-integration:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/service-integration:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/service-integration:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.opencontainers.image.created: "${BUILD_DATE}"
        org.opencontainers.image.source: "${VCS_URL}"
        org.opencontainers.image.revision: "${VCS_REF}"

  # Services below are part of the osparc-simcore stack ---------------------------

  api-server:
    image: local/api-server:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/api-server/Dockerfile
      cache_from:
        - local/api-server:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/api-server:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/api-server:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/api-server:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${API_SERVER_API_VERSION}"

  autoscaling:
    image: local/autoscaling:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/autoscaling/Dockerfile
      cache_from:
        - local/autoscaling:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/autoscaling:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/autoscaling:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/autoscaling:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${AUTOSCALING_API_VERSION}"

  catalog:
    image: local/catalog:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/catalog/Dockerfile
      cache_from:
        - local/catalog:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/catalog:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/catalog:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/catalog:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${CATALOG_API_VERSION}"

  clusters-keeper:
    image: local/clusters-keeper:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/clusters-keeper/Dockerfile
      cache_from:
        - local/clusters-keeper:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/clusters-keeper:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/clusters-keeper:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/clusters-keeper:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.opencontainers.image.created: "${BUILD_DATE}"
        org.opencontainers.image.source: "${VCS_URL}"
        org.opencontainers.image.revision: "${VCS_REF}"

  director:
    image: local/director:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/director/Dockerfile
      cache_from:
        - local/director:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/director:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/director:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/director:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${DIRECTOR_API_VERSION}"

  dask-sidecar:
    &build-dask-sidecar
    image: local/dask-sidecar:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/dask-sidecar/Dockerfile
      cache_from:
        - local/dask-sidecar:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/dask-sidecar:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/dask-sidecar:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/dask-sidecar:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"

  director-v2:
    image: local/director-v2:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/director-v2/Dockerfile
      cache_from:
        - local/director-v2:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/director-v2:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/director-v2:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/director-v2:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${DIRECTOR_V2_API_VERSION}"

  migration:
    image: local/migration:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/migration/Dockerfile
      cache_from:
        - local/migration:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/migration:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/migration:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/migration:release-github-latest
      target: production
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"

  osparc-gateway-server:
    image: local/osparc-gateway-server:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/osparc-gateway-server/Dockerfile
      cache_from:
        - local/osparc-gateway-server:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-gateway-server:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-gateway-server:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/osparc-gateway-server:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.opencontainers.image.created: "${BUILD_DATE}"
        org.opencontainers.image.source: "${VCS_URL}"
        org.opencontainers.image.revision: "${VCS_REF}"

  resource-usage-tracker:
    image: local/resource-usage-tracker:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/resource-usage-tracker/Dockerfile
      cache_from:
        - local/resource-usage-tracker:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/resource-usage-tracker:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/resource-usage-tracker:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/resource-usage-tracker:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.opencontainers.image.created: "${BUILD_DATE}"
        org.opencontainers.image.source: "${VCS_URL}"
        org.opencontainers.image.revision: "${VCS_REF}"

  static-webserver:
    image: local/static-webserver:${BUILD_TARGET:?build_target_required}
    build:
      context: ./static-webserver/client
      dockerfile: tools/qooxdoo-kit/builder/Dockerfile
      args:
        - tag=latest
        - VCS_REF=${VCS_REF}
        - VCS_REF_CLIENT=${VCS_REF_CLIENT}
        - VCS_STATUS_CLIENT=${VCS_STATUS_CLIENT}
        - VCS_URL=${VCS_URL}
      cache_from:
        - local/static-webserver:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/static-webserver:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/static-webserver:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/static-webserver:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"

  webserver:
    image: local/webserver:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/web/Dockerfile
      cache_from:
        - local/webserver:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/webserver:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/webserver:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/webserver:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VCS_URL=${VCS_URL}
        - VCS_REF=${VCS_REF}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${WEBSERVER_API_VERSION}"

  dynamic-sidecar:
    image: local/dynamic-sidecar:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/dynamic-sidecar/Dockerfile
      cache_from:
        - local/dynamic-sidecar:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/dynamic-sidecar:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/dynamic-sidecar:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/dynamic-sidecar:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"

  invitations:
    image: local/invitations:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/invitations/Dockerfile
      cache_from:
        - local/invitations:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/invitations:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/invitations:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/invitations:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${INVITATIONS_API_VERSION}"

  datcore-adapter:
    image: local/datcore-adapter:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/datcore-adapter/Dockerfile
      cache_from:
        - local/datcore-adapter:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/datcore-adapter:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/datcore-adapter:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/datcore-adapter:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${DATCORE_ADAPTER_API_VERSION}"

  storage:
    image: local/storage:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/storage/Dockerfile
      cache_from:
        - local/storage:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/storage:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/storage:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/storage:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${STORAGE_API_VERSION}"

  agent:
    image: local/agent:${BUILD_TARGET:?build_target_required}
    build:
      context: ../
      dockerfile: services/agent/Dockerfile
      args:
        - tag=latest
        - VCS_REF=${VCS_REF}
        - VCS_REF_CLIENT=${VCS_REF_CLIENT}
        - VCS_STATUS_CLIENT=${VCS_STATUS_CLIENT}
        - VCS_URL=${VCS_URL}
      cache_from:
        - local/agent:${BUILD_TARGET:?build_target_required}
        - ${DOCKER_REGISTRY:-itisfoundation}/agent:master-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/agent:staging-github-latest
        - ${DOCKER_REGISTRY:-itisfoundation}/agent:release-github-latest
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
        io.osparc.api-version: "${AGENT_API_VERSION}"
