services:
  api-server:
    healthcheck:
      interval: 30s
      timeout: 10s
      start_period: 60s
  notifications:
    healthcheck:
      interval: 30s
      timeout: 15s
      start_period: 60s
  storage:
    healthcheck:
      interval: 30s
      timeout: 15s
      start_period: 60s
