version: "3.8"
services:
  autoscaling:
    environment:
      - DASK_MONITORING_URL=tcp://dask-scheduler:8786
  dask-sidecar:
    dns: 8.8.8.8 # needed to access internet
    image: local/dask-sidecar:production
    init: true
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    volumes:
      - computational_shared_data:${SIDECAR_COMP_SERVICES_SHARED_FOLDER:-/home/scu/computational_shared_data}
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ${ETC_HOSTNAME:-/etc/hostname}:/home/scu/hostname:ro
      #   - ../../services/dask-sidecar:/devel/services/dask-sidecar
      #   - ../../packages:/devel/packages

    environment:
      DASK_LOG_FORMAT_LOCAL_DEV_ENABLED: 1
      DASK_NPROCS: 1
      DASK_SCHEDULER_URL: ${DASK_SCHEDULER_URL:-tcp://dask-scheduler:8786}
      DASK_SIDECAR_NON_USABLE_RAM: 0
      DASK_SIDECAR_NUM_NON_USABLE_CPUS: 0
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SIDECAR_COMP_SERVICES_SHARED_FOLDER: ${SIDECAR_COMP_SERVICES_SHARED_FOLDER:-/home/scu/computational_shared_data}
      SIDECAR_COMP_SERVICES_SHARED_VOLUME_NAME: computational_shared_data

    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==worker"

  dask-scheduler:
    dns: 8.8.8.8 # needed to access internet
    image: local/dask-sidecar:production
    init: true
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}-{{.Task.Slot}}"
    # volumes:
    #   - ../../services/dask-sidecar:/devel/services/dask-sidecar
    #   - ../../packages:/devel/packages
    #   # - ${ETC_HOSTNAME:-/etc/hostname}:/home/scu/hostname:ro
    environment:
      DASK_START_AS_SCHEDULER: 1
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - 8786:8786
      - 8787:8787

volumes:
  computational_shared_data:
    name: computational_shared_data
