[project]
name = "simcore-notifications-library"
version = "0.1.0"
description = "Core service library for simcore notifications"
readme = "README.md"
requires-python = "~=3.13.0"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "simcore-common-library",
  "simcore-models-library",
  "simcore-postgres-database",
  "simcore-settings-library",
  "aiofiles",
  "aiosmtplib",
  "Jinja2>=2.11.3",
]

[project.optional-dependencies]
test = [
  "aiodocker==0.24.0",
  "aiohappyeyeballs==2.6.1",
  "aiohttp==3.12.15",
  "aiosignal==1.4.0",
  "attrs==25.3.0",
  "certifi==2025.8.3",
  "charset-normalizer==3.4.3",
  "coverage==7.10.7",
  "docker==7.1.0",
  "faker==37.8.0",
  "frozenlist==1.7.0",
  "greenlet==3.2.4",
  "icdiff==2.0.7",
  "idna==3.10",
  "iniconfig==2.1.0",
  "multidict==6.6.4",
  "mypy-extensions==1.1.0",
  "mypy==1.18.2",
  "packaging==25.0",
  "pathspec==0.12.1",
  "pluggy==1.6.0",
  "pprintpp==0.4.0",
  "propcache==0.3.2",
  "pygments==2.19.2",
  "pytest-asyncio==1.2.0",
  "pytest-cov==7.0.0",
  "pytest-icdiff==0.9",
  "pytest-instafail==0.5.0",
  "pytest-mock==3.15.1",
  "pytest-runner==6.0.1",
  "pytest-sugar==1.1.1",
  "pytest==8.4.2",
  "python-dotenv==1.1.1",
  "pyyaml==6.0.3",
  "requests==2.32.5",
  "sqlalchemy2-stubs==0.0.2a38",
  "sqlalchemy==1.4.54",
  "tenacity==9.1.2",
  "termcolor==3.1.0",
  "types-aiofiles==24.1.0.20250822",
  "typing-extensions==4.15.0",
  "tzdata==2025.2",
  "urllib3==2.6.3",
  "yarl==1.20.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["notifications_library"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
