[project]
name = "simcore-celery-library"
version = "0.1.0"
description = "Core service library for simcore Celery support"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "simcore-common-library",
  "simcore-models-library",
  "simcore-service-library",
  "simcore-settings-library",
  "celery[redis]",
]

[project.optional-dependencies]
test = [
  "amqp==5.3.1",
  "anyio==4.11.0",
  "billiard==4.2.2",
  "celery==5.6.0",
  "certifi==2025.8.3",
  "charset-normalizer==3.4.3",
  "click-didyoumean==0.3.1",
  "click-plugins==1.1.1.2",
  "click-repl==0.3.0",
  "click==8.3.0",
  "coverage==7.10.7",
  "debugpy==1.8.17",
  "docker==7.1.0",
  "exceptiongroup==1.3.1",
  "faker==37.8.0",
  "fakeredis==2.31.3",
  "flexcache==0.3",
  "flexparser==0.4",
  "h11==0.16.0",
  "httpcore==1.0.9",
  "httpx==0.28.1",
  "icdiff==2.0.7",
  "idna==3.10",
  "iniconfig==2.1.0",
  "kombu==5.6.1",
  "lupa==2.5",
  "packaging==25.0",
  "pint==0.25",
  "platformdirs==4.4.0",
  "pluggy==1.6.0",
  "pprintpp==0.4.0",
  "prompt-toolkit==3.0.52",
  "psutil==7.1.0",
  "py-cpuinfo==9.0.0",
  "pygments==2.19.2",
  "pytest-asyncio==1.2.0",
  "pytest-benchmark==5.1.0",
  "pytest-celery==1.2.1",
  "pytest-cov==7.0.0",
  "pytest-docker-tools==3.1.9",
  "pytest-icdiff==0.9",
  "pytest-instafail==0.5.0",
  "pytest-mock==3.15.1",
  "pytest-runner==6.0.1",
  "pytest-sugar==1.1.1",
  "pytest==8.4.2",
  "python-dateutil==2.9.0.post0",
  "python-dotenv==1.1.1",
  "pyyaml==6.0.3",
  "redis==5.2.1",
  "requests==2.32.5",
  "setuptools==80.9.0",
  "six==1.17.0",
  "sniffio==1.3.1",
  "sortedcontainers==2.4.0",
  "tenacity==9.1.2",
  "termcolor==3.1.0",
  "typing-extensions==4.15.0",
  "tzdata==2025.2",
  "tzlocal==5.3.1",
  "urllib3==2.6.3",
  "vine==5.1.0",
  "wcwidth==0.2.14",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["celery_library"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
