[project]
name = "simcore-dask-task-models-library"
version = "0.1.0"
description = "Core service library for simcore"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "osparc", email = "support@osparc.io" }]
license = { text = "MIT" }
dependencies = [
  "simcore-common-library",
  "simcore-models-library",
  "simcore-settings-library",
  "dask[distributed]>=2023.0,<2025.0",
  "pydantic[email]>=2.10.0,<2.12.0",
  "typing_extensions>=4.0,<5.0;python_version<\"3.9\"",
]

[project.optional-dependencies]
test = [
  "coverage==7.10.7",
  "faker==37.8.0",
  "flexcache==0.3",
  "flexparser==0.4",
  "icdiff==2.0.7",
  "iniconfig==2.1.0",
  "packaging==25.0",
  "pint==0.25",
  "platformdirs==4.4.0",
  "pluggy==1.6.0",
  "pprintpp==0.4.0",
  "pygments==2.19.2",
  "pytest-asyncio==1.2.0",
  "pytest-cov==7.0.0",
  "pytest-icdiff==0.9",
  "pytest-instafail==0.5.0",
  "pytest-mock==3.15.1",
  "pytest-runner==6.0.1",
  "pytest-sugar==1.1.1",
  "pytest==8.4.2",
  "pyyaml==6.0.3",
  "termcolor==3.1.0",
  "typing-extensions==4.15.0",
  "tzdata==2025.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["dask_task_models_library"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
  "diagnostics: can be used to run diagnostics against deployed data",
  "testit: marks test to run during development",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
